export const notice = {
  data: [
    {
      noticeId: 'noticeId',
      title:
        '선거에 관한 경비는 법률이 정하는 경우를 제외하고는 정당 또는 후보자에게 부담시킬 수 없다. 국회는 의장 1인과 부의장 2인을 선출한다. 대통령은 제3항과 제4항의 사유를 지체없이 공포하여야 한다.',
      category: 'notice or event',
      created_at: '2021년 2월 2일',
    },
    {
      noticeId: 'noticeId',
      title: '유정어머니 유정이가 계속울어요 어떻게 해요...',
      category: 'notice or event',
      created_at: '2021년 2월 2일',
    },
    {
      noticeId: 'noticeId',
      title: '유정어머니 유정이가 계속울어요 어떻게 해요...',
      category: 'notice or event',
      created_at: '2021년 2월 2일',
    },
    {
      noticeId: 'noticeId',
      title: '유정어머니 유정이가 계속울어요 어떻게 해요...',
      category: 'notice or event',
      created_at: '2021년 2월 2일',
    },
    {
      noticeId: 'noticeId',
      title: '유정어머니 유정이가 계속울어요 어떻게 해요...',
      category: 'notice or event',
      created_at: '2021년 2월 2일',
    },
    {
      noticeId: 'noticeId',
      title: '유정어머니 유정이가 계속울어요 어떻게 해요...',
      category: 'notice or event',
      created_at: '2021년 2월 2일',
    },
    {
      noticeId: 'noticeId',
      title: '유정어머니 유정이가 계속울어요 어떻게 해요...',
      category: 'notice or event',
      created_at: '2021년 2월 2일',
    },
    {
      noticeId: 'noticeId',
      title: '유정어머니 유정이가 계속울어요 어떻게 해요...',
      category: 'notice or event',
      created_at: '2021년 2월 2일',
    },
    {
      noticeId: 'noticeId',
      title: '유정어머니 유정이가 계속울어요 어떻게 해요...',
      category: 'notice or event',
      created_at: '2021년 2월 2일',
    },
    {
      noticeId: 'noticeId',
      title: '유정어머니 유정이가 계속울어요 어떻게 해요...',
      category: 'notice or event',
      created_at: '2021년 2월 2일324',
    },
    {
      noticeId: 'noticeId',
      title: '유정어머니 유정이가 계속울어요 어떻게 해요...',
      category: 'notice or event',
      created_at: '2021년 2월 2일',
    },
    {
      noticeId: 'noticeId',
      title: '유정어머니 유정이가 계속울어요 어떻게 해요...',
      category: 'notice or event',
      created_at: '2021년 2월 2일',
    },
    {
      noticeId: 'noticeId',
      title: '유정어머니 유정이가 계속울어요 어떻게 해요...',
      category: 'notice or event',
      created_at: '2021년 2월 2일',
    },
    {
      noticeId: 'noticeId',
      title: '유정어머니 유정이가 계속울어요 어떻게 해요...',
      category: 'notice or event',
      created_at: '2021년 2월 2일',
    },
  ],
};
export const medicine = {
  data: [
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
  ],
};
export const timetable = {
  data: [
    {
      step: 1,
      time: '19:00 ~ 19:10',
      contents: '국민체조',
    },
    {
      step: 2,
      time: '19:10 ~ 19:15',
      contents: '간식',
    },
    {
      step: 3,
      time: '19:15 ~ 19:20',
      contents: '동요부르기',
    },
    {
      step: 4,
      time: '19:20 ~ 19:25',
      contents: '간식시간',
    },
    {
      step: 5,
      time: '19:25 ~ 19:30',
      contents: '점심',
    },
    {
      step: 6,
      time: '19:30 ~ 19:35',
      contents: '오침',
    },
    {
      step: 7,
      time: '19:35 ~ 19:40',
      contents: '야외활동',
    },
    {
      step: 8,
      time: '19:40 ~ 19:45',
      contents: '정신교육',
    },
    {
      step: 9,
      time: '19:45 ~ 19:50',
      contents: '야외활동',
    },
    {
      step: 10,
      time: '19:50 ~ 19:55',
      contents: '야외활동',
    },
    {
      step: 10,
      time: '19:55 ~ 19:59',
      contents: '야외활동',
    },
  ],
};
