export const notice = {
  data: [
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },

    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
  ],
};
export const medicine = {
  data: [
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
  ],
};
export const timetable = {
  data: [
    {
      step: 1,
      time: '19:00 ~ 19:10',
      contents: '국민체조',
    },
    {
      step: 2,
      time: '19:10 ~ 19:15',
      contents: '간식',
    },
    {
      step: 3,
      time: '19:15 ~ 19:20',
      contents: '동요부르기',
    },
    {
      step: 4,
      time: '19:20 ~ 19:25',
      contents: '간식시간',
    },
    {
      step: 5,
      time: '19:25 ~ 19:30',
      contents: '점심',
    },
    {
      step: 6,
      time: '19:30 ~ 19:35',
      contents: '오침',
    },
    {
      step: 7,
      time: '19:35 ~ 19:40',
      contents: '야외활동',
    },
    {
      step: 8,
      time: '19:40 ~ 19:45',
      contents: '정신교육',
    },
    {
      step: 9,
      time: '19:45 ~ 19:50',
      contents: '야외활동',
    },
    {
      step: 10,
      time: '19:50 ~ 19:55',
      contents: '야외활동',
    },
    {
      step: 10,
      time: '19:55 ~ 19:59',
      contents: '야외활동',
    },
  ],
};
