export const notice = {
  data: [
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },

    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
    {
      noticeId: 'noticeId',
      title: 'title',
      category: 'notice or event',
      created_at: 'created_at',
    },
  ],
};
export const medicine = {
  data: [
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
    {
      medicineId: 'medicineId',
      userId: 'userId',
      userName: 'userName',
      created_at: 'created_at',
      classId: 'classId',
      className: 'className',
    },
  ],
};
